name: x86-default-test

on:
  push:
    branches: [ main ]

jobs:

  x86-default-test:
    runs-on: macOS-11
    #runs-on: ubuntu-latest
    strategy:
      matrix:
        #api-level: [15, 16, 17, 18,19, 21, 22, 23, 24, 25, 26, 27, 28, 29 ]
        # failed version
        #api-level: [19]
        # not check version
        #api-level: [ ]
        #success version
        api-level: [15, 16, 17, 18, 21, 22, 23, 24, 25, 26, 27, 28, 29 ]
        target: [default]
        arch: [x86]
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Build project
        shell: bash
        run: |
         echo "+++++++++++++++++++++++++++++++++++++++++++++++++"
         echo "+++++++++++++++++++++++++++++++++++++++++++++++++"
         echo "++++++++++++++++++++Build project+++++++++++++++++++++++++++++"
         echo "+++++++++++++++++++++++++++++++++++++++++++++++++"
         echo "+++++++++++++++++++++++++++++++++++++++++++++++++"
         echo "-----ANDROID_HOME:-${ANDROID_HOME}"
         git clone https://oauth2:${{ secrets.GTOKEN }}@github.com/hhhaiai/FastUploadId.git
         echo "===============下载成功==============="
         ls
         echo "===============进入【FastUploadId】查看==============="
         cd FastUploadId
         ls
         chmod -R 777 *
         git config core.filemode false
         ./gradlew build
         echo "===============编译完成==============="
         ls
         apkpath=`find zip -name "*app1Debug*.apk"`
         cp $apkpath ../app1.apk
         echo "拷贝1完毕"
         apkpath=`find zip -name "*app2Debug*.apk"`
         cp $apkpath ../app2.apk
         echo "拷贝2完毕"
         cd ..
         echo "==========拷贝完毕====="
         echo "路径: $(pwd)"
         ls
      - name: cat dir
        shell: bash
        run: |
         echo "+++++++++++++++++++++++++++++++++++++++++++++++++"
         echo "+++++++++++++++++++++++++++++++++++++++++++++++++"
         echo "++++++++++++++++++++cat dir+++++++++++++++++++++++++++++"
         echo "+++++++++++++++++++++++++++++++++++++++++++++++++"
         echo "+++++++++++++++++++++++++++++++++++++++++++++++++"
         ls
         rm -rf FastUploadId/
         echo "sleep path:  $(which sleep)"

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: ${{ matrix.arch }}
          profile: Nexus 6
          avd-name: ${{ matrix.api-level }}-${{ matrix.target }}-${{ matrix.arch }}
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          script: |
            echo "====================安装并测试1======================"
            apkpath=$(find . -name "*app1Debug*.apk")
            echo "app1 path: ${apkpath}"
            echo "install commond: ${ANDROID_HOME}/platform-tools/adb install -r ${apkpath}"
            adb install -r ./app1.apk
            adb shell am start -n me.hhhaiai.fastuploadid.app1/me.hhhaiai.fastuploadid.MainActivity
            echo "=============安装1完毕,当前页面================"
            adb shell dumpsys activity|grep mResume
            echo "=============安装1完毕,查看安装列表================"
            adb shell pm list package
            sleep  120 
            echo "====================安装并测试2======================"
            adb install -r ./app2.apk
            adb shell am start -n me.hhhaiai.fastuploadid.app1/me.hhhaiai.fastuploadid.MainActivity
            echo "=============安装2完毕,当前页面================"
            adb shell dumpsys activity|grep mResume
            echo "=============安装2完毕,查看安装列表================"
            ${ANDROID_HOME}/platform-tools/adb shell pm list package
            sleep  120 
